name: Firebase Deployment

on:
  push:
    branches: 
      - main
      - development
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PRD
      deploy_option:
        description: 'Deployment Option'
        required: true
        default: 'hosting'
        type: choice
        options:
          - hosting
          - firestore
          - functions
          - storage
          - rules
          - all

jobs:
  deploy_dev:
    name: Deploy to Development
    if: github.ref == 'refs/heads/development' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'DEV')
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env.development file
        run: |
          echo "ENVIRONMENT=DEV" > .env.development
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.development
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env.development
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env.development
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env.development
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env.development
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env.development
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env.development
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env.development
          echo "ANTHROPIC_API_ENDPOINT=${{ secrets.ANTHROPIC_API_ENDPOINT }}" >> .env.development
        
      - name: Build for development
        run: npm run build:dev
      
      - name: Setup Firebase tools
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            OPTION="${{ github.event.inputs.deploy_option }}"
            if [[ "$OPTION" == "all" ]]; then
              firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --target development
            else
              firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --only $OPTION --target development
            fi
          else
            firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --target development
          fi
          
  deploy_prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'PRD')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env.production file
        run: |
          echo "ENVIRONMENT=PRD" > .env.production
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.production
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env.production
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env.production
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env.production
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env.production
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env.production
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env.production
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env.production
          echo "ANTHROPIC_API_ENDPOINT=${{ secrets.ANTHROPIC_API_ENDPOINT }}" >> .env.production
        
      - name: Build for production
        run: npm run build:prod
      
      - name: Setup Firebase tools
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            OPTION="${{ github.event.inputs.deploy_option }}"
            if [[ "$OPTION" == "all" ]]; then
              firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --target production
            else
              firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --only $OPTION --target production
            fi
          else
            firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --target production
          fi 