name: Test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test Environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PRD

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, production]
        include:
          - environment: development
            env_file: .env.development
            node_env: development
          - environment: production
            env_file: .env.production
            node_env: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        echo "ENVIRONMENT=${{ matrix.environment == 'development' && 'DEV' || 'PRD' }}" > ${{ matrix.env_file }}
        echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> ${{ matrix.env_file }}
        echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> ${{ matrix.env_file }}
        echo "APP_AI_ENABLED=true" >> ${{ matrix.env_file }}
        echo "APP_AI_MODEL=gemini-1.5-pro" >> ${{ matrix.env_file }}
        echo "APP_AI_WEEKLY_LIMIT=10" >> ${{ matrix.env_file }}
      
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: ${{ matrix.node_env }}
      
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: ${{ matrix.environment }} 